CREATE TABLE TEST_TABLE (
    id INT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    age INT NOT NULL
);

INSERT INTO TEST_TABLE VALUES (1, 'Alice', 30);
INSERT INTO TEST_TABLE VALUES (2, 'Bob', 25);